/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#173bab',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#ffafd3',
        'surface-container-high': '#dce9ff',
        'on-primary-fixed': '#001453',
        surface: '#f8f9ff',
        error: '#ba1a1a',
        'on-background': '#0b1c30',
        'on-secondary-fixed': '#2a1700',
        'surface-container': '#e5eeff',
        'on-primary-container': '#a8b8ff',
        'tertiary-container': '#8b1a5e',
        'outline-variant': '#c4c5d5',
        'surface-container-low': '#eff4ff',
        'primary-fixed': '#dde1ff',
        'on-tertiary-container': '#ff9dcc',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#b8c4ff',
        'on-tertiary-fixed': '#3d0026',
        outline: '#757684',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#653e00',
        'on-secondary-container': '#684000',
        'primary-container': '#1e40af',
        'on-surface': '#0b1c30',
        'on-tertiary-fixed-variant': '#85145a',
        'surface-bright': '#f8f9ff',
        'on-error': '#ffffff',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#ffb95f',
        'surface-variant': '#d3e4fe',
        'tertiary-fixed': '#ffd8e7',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eaf1ff',
        'on-error-container': '#93000a',
        'surface-tint': '#3755c3',
        'secondary-container': '#fea619',
        'surface-container-highest': '#d3e4fe',
        tertiary: '#6a0045',
        'on-surface-variant': '#444653',
        'inverse-primary': '#b8c4ff',
        primary: '#00288e',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#213145',
        background: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        secondary: '#855300',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1280px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        unit: '8px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
      },
      boxShadow: {
        lifted: '0px 4px 20px rgba(30, 64, 175, 0.08)',
        overlay: '0px 10px 30px rgba(15, 23, 42, 0.12)',
      },
    },
  },
  plugins: [],
};
